### PR TITLE
Bump to QEMU 4.2.0

### LINKED ISSUE #23: "bad record MAC" for linux/s390x
I am running into the following error:
```
#11 [builder 5/8] RUN go mod download
#11 0.445 go: github.com/pkg/errors@v0.9.1: Get https://proxy.golang.org/github.com/pkg/errors/@v/v0.9.1.mod: local error: tls: bad record MAC
#11 ERROR: executor failed running [/bin/sh -c go mod download]: buildkit-runc did not terminate successfully
```

I am using buildx under GCB - https://github.com/dims/go-runner.Looks like the same problem was spotted in another arch as well https://github.com/moby/moby/issues/40240

Per https://bugs.launchpad.net/qemu/+bug/1847232, the problem has been fixed in QEMU 4.2

### PR DESCRIPTION
**Pull request by dims**
Fixes https://github.com/docker/binfmt/issues/23

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by dims** [comment]
cc @StefanScherer  @justincormack

**Comment by dims** [comment]
Never mind looks like this is a big deal and not a one liner !
https://ci-next.docker.com/public/blue/organizations/jenkins/binfmt/detail/PR-24/1/pipeline

Looks like the qemu fork needs to be updated
https://github.com/moby/qemu

**Comment by dims** [comment]
Looking at the differences between the forked and upstream qemu for say 4.0.0, 4.1.0:
- https://github.com/qemu/qemu/compare/v4.0.0...moby:moby/v4.0.0
- https://github.com/qemu/qemu/compare/v4.1.0...moby:moby/v4.1.0

Looks like the only difference is:
https://github.com/qemu/qemu/commit/7fde1629dc7393ce40fff7841cf3efeb6650e58b

**Comment by dims** [comment]
Funny, looks like golang already tolerates 33 and 64. So we don't really need the fork

64 was added first in https://github.com/golang/go/commit/2aef675000e71daeef77c0fb3379bcd142e48959
and then 33/32 were as well https://github.com/golang/go/commit/c0e5485bd59827d6def05020b201133982a52790

**Comment by dims** [comment]
cc @thaJeztah @justincormack @tiborvass

**Comment by thaJeztah** [comment]
Nice find! Looks like we should be able to archive https://github.com/moby/qemu then?

**Comment by tuonga** [comment]
Ooops.  Guess I could've looked under Golang when I was working on this.  😬

**Comment by dims** [comment]
Bonus : since those 2 golang patches are in golang 1.11 already and currently even 1.11 is [gone out of support](https://golang.org/doc/devel/release.html#policy), we should totally moth ball  the `moby/qemu` repo.

**Review by StefanScherer — APPROVED** [review]
Thanks for finding and linking the fixes in golang. This looks reasonable to me.

LGTM

**Comment by thaJeztah** [comment]
Oh; I see there's one open PR against the fork; https://github.com/moby/qemu/pull/7 - @tuonga do you know if that's still needed, and if so, should that be upstreamed directly?

**Comment by tuonga** [comment]
Tibor can better comment on the outstanding PR but the main purpose was to
get Docker in Docker working under QEMU.  Most if not all changes in there
are probably worth upstreaming.

**Comment by thaJeztah** [comment]
Also had a chat with @justincormack about archiving the moby/qemu repo; he mentioned it would probably be ok for this repository to use the upstream, but that the moby/qemu repo would still be useful as a place to work on patches (to be upstreamed later)

**Comment by dims** [comment]
@justincormack @thaJeztah Done! i've updated this PR to point to qemu/qemu and 4.2.0. Let's ship it! :)

**Comment by justincormack** [comment]
I don't think there is any point using this repo at all if it doesn't carry patches, I opened https://github.com/linuxkit/linuxkit/pull/3515 to just update LinuxKit to use 4.2.0, this was the original source of the binfmt package.

**Comment by dims** [comment]
@justincormack so we can close out this repo as well? Nice!

**Comment by justincormack** [comment]
Closing in favour of upstream LinuxKit

**Pull request closed without merging**
